### ISSUE TITLE
TestCharsets fails with Golang 1.6

### ISSUE THREAD

**Issue by onlyjob** [paulrosania/go-charset#1]
```
=== RUN   TestCharsets
--- FAIL: TestCharsets (0.00s)
        iconv_test.go:38: test 0
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
        panic: runtime error: cgo argument has Go pointer to Go pointer
```

Apparently Go pointer to Go pointer is no longer allowed: https://github.com/golang/go/issues/12416

**Comment by onlyjob** [comment]
Or maybe this problem is due to absence of test data in `/usr/local/lib/go-charset/datafiles`...
Anyway error message is rather confusing... Please investigate.

**Comment by mantri** [comment]
When I try to run tsc.go, I get this error:
charset: cannot open "charsets.json": open /usr/local/lib/go-charset/datafiles/charsets.json: no such file or directory

**Comment by tessro** [comment]
I'm sure you have long since moved on, but I finally identified and fixed the cgo issue. Closing this.
